fastlane_version "1.55.0"

default_platform :ios

platform :ios do
  before_all do
    # Configure Slack
    ENV["SLACK_URL"] ||= "https://hooks.slack.com/services/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"
    ENV["FL_SLACK_USERNAME"] ||= "TestFlight"
    ENV["FL_SLACK_ICON_URL"] ||= "http://canvas-slack.s3.amazonaws.com/avatars/testflight.png"
    ENV["FL_SLACK_CHANNEL"] ||= "#general"

    # Configure Hockey
    ENV["FL_HOCKEY_API_TOKEN"] ||= "6be9271230f44ea2863409a15eb9a54f"
    ENV["FL_HOCKEY_RELEASE_TYPE"] ||= "1"
    ENV["FL_HOCKEY_REPOSITORY_URL"] ||= "https://github.com/usecanvas/ios"
    ENV["FL_HOCKEY_COMMIT_SHA"] ||= `git rev-parse HEAD`.chomp
    ENV["FL_HOCKEY_UPLOAD_DSYM_ONLY"] ||= "1"
    ENV["FL_HOCKEY_NOTIFY"] ||= "0"
    ENV["FL_HOCKEY_PUBLIC_IDENTIFIER"] ||= "0d558bb833514f31a4be3f9bfeafc43d"

    # Make sure everything is committed.
    ensure_git_status_clean

    # Build dependencies
    sh 'rake bootstrap' unless ENV["SKIP_CARTHAGE"] == 1
  end

  desc "Submit a new beta build to TestFlight"
  lane :beta do
    # Build
    gym(scheme: "Canvas")

    # Get version number
    short_version = get_ipa_info_plist_value(key: "CFBundleShortVersionString")
    version = get_ipa_info_plist_value(key: "CFBundleVersion")
    full_version = "#{short_version} (#{version})"

    # Get changelog
    changelog = prompt(text: "Enter Release Notes for this release:", multi_line_end_keyword: "END").chomp

    # Upload to dSYM Hockey
    hockey(notes: changelog)

    # Upload to TestFlight
    pilot(changelog: changelog)

    # Create git tag
    sh "git tag v#{short_version}-#{version} && git push --tags"

    # Notify in Slack
    slack(message: "Version #{full_version} is available on TestFlight! Release Notes:\n\n#{changelog}\n", success: true)
  end
end
